language: php

php:
  - 5.6
  - 7

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: precise
    - php: 5.5
      dist: trusty

sudo: false
cache:
  directories:
    - $HOME/.composer/cache

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/27e6f370d800d3c06e68
    on_success: always
    on_failure: always
    on_start: never

before_script: composer install --dev
script: ./vendor/bin/phpunit
