language: php

php:
  - 5.6
  - 7

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: precise
    - php: 5.5
      dist: trusty

sudo: false
cache:
  directories:
    - $HOME/.composer/cache

before_script: composer install --dev
script: ./vendor/bin/phpunit
